In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("abalone.csv")

In [30]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [31]:
df.head()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [32]:
df.tail()

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12

In [33]:
df.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [25]:
df

df = pd.read_csv('../input/abalone.csv')
Sex Length Diameter Height Whole weight Shucked weight Viscera weight Shell weight                                    Rings
M   0.455  0.365    0.095  0.514        0.2245         0.101          0.15                                               15
    0.35   0.265    0.09   0.2255       0.0995         0.0485         0.07                                                7
F   0.53   0.42     0.135  0.677        0.2565         0.1415         0.21                                                9
M   0.44   0.365    0.125  0.516        0.2155         0.114          0.155                                              10
...                                                                                                                     ...
F   0.565  0.45     0.165  0.887        0.37           0.239          0.249                                              11
M   0.59   0.44     0.135  0.966        0.439          0.2145         0.2605                                             10
    0.6    0.475    0.205  1.176        0.5255         0.2875         0.308                                               9
F   0.625  0.485    0.15   1.0945       0.531          0.261          0.296                                              10
M   0.71   0.555    0.195  1.9485       0.9455         0.3765         0.495                                              12

[4178 rows x 1 columns]

In [34]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [35]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [38]:
## categorical variables: sex
## numerical variables: length, diameter, height, whole weight, shucked weight, viscera weight, shell weight, 
## target variable: Rings

In [39]:
df["Sex"].value_counts()

Sex
M    1528
I    1342
F    1307
Name: count, dtype: int64

In [40]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder() 
df["Sex"] = label_encoder.fit_transform(df["Sex"])

In [41]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [45]:
df.columns

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')

In [43]:
X = df.drop("Rings", axis=1)
y = df["Rings"]

In [46]:
X

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0       2   0.455     0.365   0.095        0.5140          0.2245   
1       2   0.350     0.265   0.090        0.2255          0.0995   
2       0   0.530     0.420   0.135        0.6770          0.2565   
3       2   0.440     0.365   0.125        0.5160          0.2155   
4       1   0.330     0.255   0.080        0.2050          0.0895   
...   ...     ...       ...     ...           ...             ...   
4172    0   0.565     0.450   0.165        0.8870          0.3700   
4173    2   0.590     0.440   0.135        0.9660          0.4390   
4174    2   0.600     0.475   0.205        1.1760          0.5255   
4175    0   0.625     0.485   0.150        1.0945          0.5310   
4176    2   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  
0             0.1010        0.1500  
1             0.0485        0.0700  
2             0.1415        0.2100  
3             0.1140        0.1550  
4             0.0395        0.0550  
...              ...           ...  
4172          0.2390        0.2490  
4173          0.2145        0.2605  
4174          0.2875        0.3080  
4175          0.2610        0.2960  
4176          0.3765        0.4950  

[4177 rows x 8 columns]

In [47]:
y

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
len(X_train), len(y_train)

(3341, 3341)

In [50]:
len(X_test), len(y_test)

(836, 836)

In [51]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [52]:
lr.fit(X_train, y_train)

LinearRegression()

In [53]:
lr.score(X_test, y_test)

0.5323381317508206

In [54]:
demo_input = X_test.iloc[0].to_numpy()

In [55]:
lr.predict([demo_input])

c:\Users\G TECH\MINICONDA\envs\housing\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.69320349])

In [56]:
lr.predict([X_test.iloc[0]])

c:\Users\G TECH\MINICONDA\envs\housing\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.69320349])

In [58]:
y_test.iloc[0]

np.int64(9)

In [59]:
lr.coef_

array([  0.08418964,  -1.53945918,  13.59793755,  11.44839996,
         9.15739582, -20.68102468,  -8.75282231,   8.64847518])

In [60]:
lr.intercept_

np.float64(2.8671380390954244)

In [61]:
lr.n_features_in_

8

In [62]:
lr.feature_names_in_

array(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight',
       'Shucked weight', 'Viscera weight', 'Shell weight'], dtype=object)

In [63]:
lr.coef_

array([  0.08418964,  -1.53945918,  13.59793755,  11.44839996,
         9.15739582, -20.68102468,  -8.75282231,   8.64847518])

In [64]:
lr.coef_[0]

np.float64(0.084189638051748)

In [65]:
lr.coef_[5]

np.float64(-20.6810246766746)

In [66]:
X_test.iloc[1]["Sex"]

np.float64(2.0)

In [71]:
Sex = X_test.iloc[0]["Sex"]
Length = X_test.iloc[0]["Length"]
Diameter = X_test.iloc[0]["Diameter"]
Height = X_test.iloc[0]["Height"]
Whole_weight = X_test.iloc[0]["Whole weight"]
Shucked_weight = X_test.iloc[0]["Shucked weight"]
Viscera_weight = X_test.iloc[0]["Viscera weight"]
Shell_weight = X_test.iloc[0]["Shell weight"]

In [76]:
predicted_result = (
    lr.coef_[0] * Sex + lr.coef_[1] * Length + lr.coef_[2] * Diameter + lr.coef_[3] * Height + lr.coef_[4] * Whole_weight +
    lr.coef_[5] * Shucked_weight + lr.coef_[6] * Viscera_weight + lr.coef_[7] * Shell_weight + lr.intercept_ )

In [77]:
predicted_result

np.float64(11.693203491960539)

In [78]:
lr.predict([X_test.iloc[0]])

c:\Users\G TECH\MINICONDA\envs\housing\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.69320349])